/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mrhan_console_ConsoleOutputStream */

#ifndef _Included_com_mrhan_console_ConsoleOutputStream
#define _Included_com_mrhan_console_ConsoleOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mrhan_console_ConsoleOutputStream
 * Method:    write
 * Signature: (J)V
 */
JNIEXPORT 
void JNICALL Java_com_mrhan_console_ConsoleOutputStream_write(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
