/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mrhan_console_Console */

#ifndef _Included_com_mrhan_console_Console
#define _Included_com_mrhan_console_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mrhan_console_Console
 * Method:    createDos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mrhan_console_Console_createDos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
