/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mrhan_console_ConsoleInputStream */

#ifndef _Included_com_mrhan_console_ConsoleInputStream
#define _Included_com_mrhan_console_ConsoleInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mrhan_console_ConsoleInputStream_MAX_SKIP_BUFFER_SIZE
#define com_mrhan_console_ConsoleInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     com_mrhan_console_ConsoleInputStream
 * Method:    read
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mrhan_console_ConsoleInputStream_read
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
